### PR TITLE
Add UL pixel resolution histograms for all years

### PR DESCRIPTION
**Pull request by lcorcodilos**
These additional pixel resolution histogram files will eventually be used by a new UL config akin to [PixelPluginsPhase1_cfi.py](https://github.com/cms-sw/cmssw/blob/master/FastSimulation/TrackingRecHitProducer/python/PixelPluginsPhase1_cfi.py). I'll be making a separate PR later today or tomorrow to cmssw for this change. However, this config will be "off" by default because UL FastSim production has already begun. These data files should nonetheless be preserved here and there will be an ability to turn them "on" in the cmssw block of code for future studies or private production.

Among the ROOT files, I've also included a txt file that explain the numerical codes at the end of each file name. This information explains to what part of the detector the file maps (year/detector layer) and from which PIXELAV template files the resolution were generated ("Files").

@pmaksim1 @ozamram @tvami

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#34812

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmssw/pull/34812

**Comment by smuzaffar** [comment]
+externals
only new files. This should go in with https://github.com/cms-sw/cmssw/pull/34812

**Comment by smuzaffar** [comment]
closing this as https://github.com/cms-sw/cmssw/pull/34812 ( which requires it) is closed too. Open a new PR if needed

**Pull request closed without merging**
