### PR TITLE
update resolution files

### PR DESCRIPTION
**Pull request by matt-komm**
see CMSSW PR https://github.com/cms-sw/cmssw/pull/14843

### CODE REVIEW

**Comment by lveldere** [comment]
+1 
(pro forma for fastsim)

**Comment by lveldere** [comment]
Hi @iahmad-khan 

I'm not familiar with how CMSSW builds interaction with these cms-data repositories.
Therefore, could you tell me when we may expect these files to be visible in an IB?

Thanks

Lukas

**Comment by iahmad-khan** [comment]
@lveldere  when this completes and finally gets merged , https://github.com/cms-sw/cmsdist/pull/2347

**Comment by smuzaffar** [comment]
this is now merged for next (23h) 81X IB.

**Pull request merged**
