### PR TITLE
New pixel resolution files, to go along with the code in 10.2.0

### PR DESCRIPTION
**Pull request by pmaksim1**
Needed by the new pixel fast sim code.  (Note that the format of the root files changed.  I kept the old obsolete files for now.  The new files are needed -- and can only be read -- by the new pixel fast sim code, PR coming in shortly.)

### CODE REVIEW

**Comment by mrodozov** [comment]
assign fastsim

**Comment by pmaksim1** [comment]
Oops, forgot to mention that this requires the PR from cms-data to work:
https://github.com/cms-data/FastSimulation-TrackingRecHitProducer/pull/3

(so testing without it won't work).

**Comment by smuzaffar** [comment]
@mdhildreth,@ssekmen,@lveldere,@civanch , can you please sign this data external?

**Comment by pmaksim1** [comment]
Adding also @cmantill (who produced these files) and @lcorcodilos (who tested them).

**Comment by pmaksim1** [comment]
Hey, @ssekmen, any news with this?

**Comment by ssekmen** [comment]
+1

**Comment by ssekmen** [comment]
please test

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/4196 include the changes for 10.3.X.

**Pull request merged**
